import {ResponseType} from './types';

export const response: ResponseType = {
  success: true,
  result: [
    {
      card_id: 1,
      reviewer_id: 2,
      name: 'Помыть',
      reward: 1000,
      photo_required: true,
      video_required: false,
      schedule: [true, false, true, true, false, false, false],
      period_start: '2023-04-17 10:00:00',
      period_stop: null,
      type: 'TASKS',
      description: 'Помыть посуду',
    },
    {
      card_id: 2,
      reviewer_id: 2,
      name: 'Помыть посуду',
      reward: 1000,
      photo_required: true,
      video_required: false,
      schedule: [true, false, true, true, false, false, false],
      period_start: '2023-04-17 10:00:00',
      period_stop: null,
      type: 'ALL',
    },
    {
      card_id: 3,
      reviewer_id: 2,
      name: 'Помыть посуду',
      reward: 1000,
      photo_required: true,
      video_required: false,
      schedule: [true, false, true, true, false, false, false],
      period_start: '2023-04-17 10:00:00',
      period_stop: null,
      type: 'TASKS',
    },
    {
      card_id: 4,
      reviewer_id: 2,
      name: 'Помыть посуду',
      reward: 1000,
      photo_required: true,
      video_required: false,
      schedule: [true, false, true, true, false, false, false],
      period_start: '2023-04-17 10:00:00',
      period_stop: null,
      type: 'TASKS',
    },
    {
      card_id: 5,
      reviewer_id: 2,
      name: 'Помыть посуду',
      reward: 1000,
      photo_required: true,
      video_required: false,
      schedule: [true, false, true, true, false, false, false],
      period_start: '2023-04-17 10:00:00',
      period_stop: null,
      type: 'TASKS',
    },
    {
      card_id: 6,
      reviewer_id: 2,
      name: 'Помыть посуду',
      reward: 1000,
      photo_required: true,
      video_required: false,
      schedule: [true, false, true, true, false, false, false],
      period_start: '2023-04-17 10:00:00',
      period_stop: null,
      type: 'ALL',
    },
    {
      card_id: 7,
      reviewer_id: 2,
      name: 'Помыть посуду',
      reward: 1000,
      photo_required: true,
      video_required: false,
      schedule: [true, false, true, true, false, false, false],
      period_start: '2023-04-17 10:00:00',
      period_stop: null,
      type: 'ALL',
    },
    {
      card_id: 8,
      reviewer_id: 2,
      name: 'Помыть посуду',
      reward: 1000,
      photo_required: true,
      video_required: false,
      schedule: [true, false, true, true, false, false, false],
      period_start: '2023-04-17 10:00:00',
      period_stop: null,
      type: 'ALL',
    },
    {
      card_id: 9,
      reviewer_id: 2,
      name: 'Помыть посуду',
      reward: 1000,
      photo_required: true,
      video_required: false,
      schedule: [true, false, true, true, false, false, false],
      period_start: '2023-04-17 10:00:00',
      period_stop: null,
      type: 'ALL',
    },
    {
      card_id: 10,
      reviewer_id: 2,
      name: 'Помыть посуду',
      reward: 1000,
      photo_required: true,
      video_required: false,
      schedule: [true, false, true, true, false, false, false],
      period_start: '2023-04-17 10:00:00',
      period_stop: null,
      type: 'ALL',
    },
    {
      card_id: 123,
      reviewer_id: 2,
      name: 'Помыть посуду',
      reward: 1000,
      photo_required: true,
      video_required: false,
      schedule: [true, false, true, true, false, false, false],
      period_start: '2023-04-17 10:00:00',
      period_stop: null,
      type: 'ALL',
    },
    {
      card_id: 123,
      reviewer_id: 2,
      name: 'Помыть посуду',
      reward: 1000,
      photo_required: true,
      video_required: false,
      schedule: [true, false, true, true, false, false, false],
      period_start: '2023-04-17 10:00:00',
      period_stop: null,
      type: 'ALL',
    },
    {
      card_id: 123,
      reviewer_id: 2,
      name: 'Помыть посуду',
      reward: 1000,
      photo_required: true,
      video_required: false,
      schedule: [true, false, true, true, false, false, false],
      period_start: '2023-04-17 10:00:00',
      period_stop: null,
      type: 'ALL',
    },
    {
      card_id: 123,
      reviewer_id: 2,
      name: 'Помыть посуду',
      reward: 1000,
      photo_required: true,
      video_required: false,
      schedule: [true, false, true, true, false, false, false],
      period_start: '2023-04-17 10:00:00',
      period_stop: null,
      type: 'ALL',
    },
    {
      card_id: 123,
      reviewer_id: 2,
      name: 'Помыть посуду',
      reward: 1000,
      photo_required: true,
      video_required: false,
      schedule: [true, false, true, true, false, false, false],
      period_start: '2023-04-17 10:00:00',
      period_stop: null,
      type: 'ALL',
    },
    {
      card_id: 123,
      reviewer_id: 2,
      name: 'Помыть посуду',
      reward: 1000,
      photo_required: true,
      video_required: false,
      schedule: [true, false, true, true, false, false, false],
      period_start: '2023-04-17 10:00:00',
      period_stop: null,
      type: 'ALL',
    },
    {
      card_id: 123,
      reviewer_id: 2,
      name: 'Помыть посуду',
      reward: 1000,
      photo_required: true,
      video_required: false,
      schedule: [true, false, true, true, false, false, false],
      period_start: '2023-04-17 10:00:00',
      period_stop: null,
      type: 'ALL',
    },
    {
      card_id: 123,
      reviewer_id: 2,
      name: 'Помыть посуду',
      reward: 1000,
      photo_required: true,
      video_required: false,
      schedule: [true, false, true, true, false, false, false],
      period_start: '2023-04-17 10:00:00',
      period_stop: null,
      type: 'ALL',
    },
    {
      card_id: 123,
      reviewer_id: 2,
      name: 'Помыть посуду',
      reward: 1000,
      photo_required: true,
      video_required: false,
      schedule: [true, false, true, true, false, false, false],
      period_start: '2023-04-17 10:00:00',
      period_stop: null,
      type: 'ALL',
    },
    {
      card_id: 123,
      reviewer_id: 2,
      name: 'Помыть посуду',
      reward: 1000,
      photo_required: true,
      video_required: false,
      schedule: [true, false, true, true, false, false, false],
      period_start: '2023-04-17 10:00:00',
      period_stop: null,
      type: 'ALL',
    },
    {
      card_id: 123,
      reviewer_id: 2,
      name: 'Помыть посуду',
      reward: 1000,
      photo_required: true,
      video_required: false,
      schedule: [true, false, true, true, false, false, false],
      period_start: '2023-04-17 10:00:00',
      period_stop: null,
      type: 'ALL',
    },
    {
      card_id: 123,
      reviewer_id: 2,
      name: 'Помыть посуду',
      reward: 1000,
      photo_required: true,
      video_required: false,
      schedule: [true, false, true, true, false, false, false],
      period_start: '2023-04-17 10:00:00',
      period_stop: null,
      type: 'ALL',
    },
    {
      card_id: 123,
      reviewer_id: 2,
      name: 'Помыть посуду',
      reward: 1000,
      photo_required: true,
      video_required: false,
      schedule: [true, false, true, true, false, false, false],
      period_start: '2023-04-17 10:00:00',
      period_stop: null,
      type: 'ALL',
    },
    {
      card_id: 123,
      reviewer_id: 2,
      name: 'Помыть посуду',
      reward: 1000,
      photo_required: true,
      video_required: false,
      schedule: [true, false, true, true, false, false, false],
      period_start: '2023-04-17 10:00:00',
      period_stop: null,
      type: 'ALL',
    },
    {
      card_id: 123,
      reviewer_id: 2,
      name: 'Помыть посуду',
      reward: 1000,
      photo_required: true,
      video_required: false,
      schedule: [true, false, true, true, false, false, false],
      period_start: '2023-04-17 10:00:00',
      period_stop: null,
      type: 'ALL',
    },
    {
      card_id: 123,
      reviewer_id: 2,
      name: 'Помыть посуду',
      reward: 1000,
      photo_required: true,
      video_required: false,
      schedule: [true, false, true, true, false, false, false],
      period_start: '2023-04-17 10:00:00',
      period_stop: null,
      type: 'ALL',
    },
    {
      card_id: 123,
      reviewer_id: 2,
      name: 'Помыть посуду',
      reward: 1000,
      photo_required: true,
      video_required: false,
      schedule: [true, false, true, true, false, false, false],
      period_start: '2023-04-17 10:00:00',
      period_stop: null,
      type: 'ALL',
    },
    {
      card_id: 123,
      reviewer_id: 2,
      name: 'Помыть посуду',
      reward: 1000,
      photo_required: true,
      video_required: false,
      schedule: [true, false, true, true, false, false, false],
      period_start: '2023-04-17 10:00:00',
      period_stop: null,
      type: 'ALL',
    },
    {
      card_id: 123,
      reviewer_id: 2,
      name: 'Помыть посуду',
      reward: 1000,
      photo_required: true,
      video_required: false,
      schedule: [true, false, true, true, false, false, false],
      period_start: '2023-04-17 10:00:00',
      period_stop: null,
      type: 'ALL',
    },
    {
      card_id: 123,
      reviewer_id: 2,
      name: 'Помыть посуду',
      reward: 1000,
      photo_required: true,
      video_required: false,
      schedule: [true, false, true, true, false, false, false],
      period_start: '2023-04-17 10:00:00',
      period_stop: null,
      type: 'ALL',
    },
    {
      card_id: 123,
      reviewer_id: 2,
      name: 'Помыть посуду',
      reward: 1000,
      photo_required: true,
      video_required: false,
      schedule: [true, false, true, true, false, false, false],
      period_start: '2023-04-17 10:00:00',
      period_stop: null,
      type: 'ALL',
    },
    {
      card_id: 123,
      reviewer_id: 2,
      name: 'Помыть посуду',
      reward: 1000,
      photo_required: true,
      video_required: false,
      schedule: [true, false, true, true, false, false, false],
      period_start: '2023-04-17 10:00:00',
      period_stop: null,
      type: 'ALL',
    },
    {
      card_id: 123,
      reviewer_id: 2,
      name: 'Помыть посуду',
      reward: 1000,
      photo_required: true,
      video_required: false,
      schedule: [true, false, true, true, false, false, false],
      period_start: '2023-04-17 10:00:00',
      period_stop: null,
      type: 'ALL',
    },
    {
      card_id: 123,
      reviewer_id: 2,
      name: 'Помыть посуду',
      reward: 1000,
      photo_required: true,
      video_required: false,
      schedule: [true, false, true, true, false, false, false],
      period_start: '2023-04-17 10:00:00',
      period_stop: null,
      type: 'ALL',
    },
    {
      card_id: 123,
      reviewer_id: 2,
      name: 'Помыть посуду',
      reward: 1000,
      photo_required: true,
      video_required: false,
      schedule: [true, false, true, true, false, false, false],
      period_start: '2023-04-17 10:00:00',
      period_stop: null,
      type: 'ALL',
    },
    {
      card_id: 123,
      reviewer_id: 2,
      name: 'Помыть посуду',
      reward: 1000,
      photo_required: true,
      video_required: false,
      schedule: [true, false, true, true, false, false, false],
      period_start: '2023-04-17 10:00:00',
      period_stop: null,
      type: 'ALL',
    },
    {
      card_id: 123,
      reviewer_id: 2,
      name: 'Помыть посуду',
      reward: 1000,
      photo_required: true,
      video_required: false,
      schedule: [true, false, true, true, false, false, false],
      period_start: '2023-04-17 10:00:00',
      period_stop: null,
      type: 'ALL',
    },
    {
      card_id: 123,
      reviewer_id: 2,
      name: 'Помыть посуду',
      reward: 1000,
      photo_required: true,
      video_required: false,
      schedule: [true, false, true, true, false, false, false],
      period_start: '2023-04-17 10:00:00',
      period_stop: null,
      type: 'ALL',
    },
    {
      card_id: 123,
      reviewer_id: 2,
      name: 'Помыть посуду',
      reward: 1000,
      photo_required: true,
      video_required: false,
      schedule: [true, false, true, true, false, false, false],
      period_start: '2023-04-17 10:00:00',
      period_stop: null,
      type: 'ALL',
    },
    {
      card_id: 123,
      reviewer_id: 2,
      name: 'Помыть посуду',
      reward: 1000,
      photo_required: true,
      video_required: false,
      schedule: [true, false, true, true, false, false, false],
      period_start: '2023-04-17 10:00:00',
      period_stop: null,
      type: 'ALL',
    },
  ],
};
